### ISSUE TITLE
Unknown versions

### ISSUE THREAD

**Issue by daniel-bartley** [justmiles/cq-source-crowdstrike#6]
Not sure if the problem is in the source plugin or something else

``` # config.yaml

kind: source
spec:
  name: "crowdstrike"
  registry: "github"
  path: "justmiles/crowdstrike"
  version: "v0.0.4"
  tables: ["*"]
  destinations: ["bigquery"]

---

kind: destination
spec:
  name: bigquery
  path: cloudquery/bigquery
  version: "v3.3.0"
  write_mode: "append"
  spec:
    project_id: ${PROJECT_ID}
    dataset_id: ${DATASET_ID}
    dataset_location: "US"
    time_partitioning: "day"

```

$ cloudquery -v
cloudquery version 2.4.1

$ cloudquery.exe sync ./config.yaml
Loading spec(s) from ./config.yaml
Downloading https://github.com/justmiles/cq-source-crowdstrike/releases/download/v0.0.4/cq-source-crowdstrike_windows_amd64.zip
Downloading 100% |█████████████████████████████████████████████████████| (11/11 MB, 11 MB/s)         
Error: failed to sync source crowdstrike, unknown versions [v2]

**Comment by daniel-bartley** [comment]
```
$ cloudquery --version
cloudquery version 3.14.4

$ cloudquery.exe sync config.yaml
Loading spec(s) from config.yaml
Starting migration for: crowdstrike (v0.0.4) -> [bigquery (v3.3.0)]
Migration completed successfully.
Starting sync for: crowdstrike (v0.0.4) -> [bigquery (v3.3.0)]
| Syncing resources... (0/-, 0 resources/hr) [2s] panic: [GET /discover/queries/hosts/v1][403] queryHostsForbidden  &{Errors:[{Code:403 Message:access denied, authorization failed}] Meta:PoweredBy:crowdstrike-api-gateway QueryTime:1.67e-07 TraceID:8bd03b71-02fc-4873-b292-50d203266f51}}
[BODY {"errors":[{"code":403,"message":"access denied, authorization failed"}],"meta":{"powered_by":"crowdstrike-api-gateway","query_time":1.67e-7,"trace_id":"8bd03b71-02fc-4873-b292-50d203266f51"}}]

goroutine 36 [running]:
github.com/justmiles/cq-source-crowdstrike/resources.getHostIds.func1()
        /home/runner/work/cq-source-crowdstrike/cq-source-crowdstrike/resources/discover_applications.go:38 +0x20d
created by github.com/justmiles/cq-source-crowdstrike/resources.getHostIds
        /home/runner/work/cq-source-crowdstrike/cq-source-crowdstrike/resources/discover_applications.go:28 +0x14a
Error: failed to sync v2 source crowdstrike: rpc error: code = Unavailable desc = error reading from server: read unix @->C:\Users\1363913\AppData\Local\Temp\cq-HGgzmvMQjRXYsnnC.sock: wsarecv: An existing connection was forcibly closed by the remote host
```

**Comment by justmiles** [comment]
This was resolved in discord, but copying here for context:

> Erez — 08/29/2023 2:20 AM
> Hi, can you try updating the CLI to the latest version v3.14.4 ? I believe the version you're using is too old to be used > with the plugins versions that are configured in your spec file
> See https://www.cloudquery.io/docs/quickstart/windows on how to upgrade
